# Generated by Django 5.1.4 on 2024-12-13 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0004_offer_blockchain_tx_tender_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='tag',
            field=models.TextField(blank=True, null=True),
        ),
    ]
