# Generated by Django 5.1.4 on 2024-12-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0005_tender_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
